- name: Run mongo container
  docker_container:
    name: 'some-mongo'
    restart_policy: 'always'
    published_ports: '27017:27017'
    volumes:
      - /data/mongo:/data/db
    image: mongo:4.4.1
