# This playbook deploys the website app

- hosts: apps

  roles:
    - {
        role: "service",
        service_name: "website",
        docker_env: {
            GAME_ASSETS_URL: "https://{{ game_assets_domain }}",
            ARENA_URL: "https://{{ arena_domain }}",
            AUTH_URL: "https://{{ auth_domain }}",
            CMS_URL: "https://{{ cms_domain }}",
            CMS_TOKEN: "{{ cms_token }}",
            SESSION_SECRET: "{{ session_secret | string }}",
            PORT: "{{ external_port | string }}", # The port where to serve the app
            SERVICE: "website2",
            ENV: "{{ env }}",
        },
        # Some parameters are commented as they are inherited in roles
        # registry: "{{ registry }}",
        # registry_username: "{{ registry_username }}",
        # registry_password: "{{ registry_password }}",
        # docker_image: "{{ docker_image }}",
        port_container: "{{ external_port | int }}",
        port_nginx: "{{ internal_port | int }}",
        # domain: "{{ domain }}",
        # cerbot_email: "{{ certbot_email }}",
      }
