# This playbook deploys the Robots app

- hosts: apps

  roles:
    - {
        role: "service",
        service_name: "robots",
        docker_env: {
            PORT: "{{ service_robots_external_port | string }}",
            PRIVATE_KEY: "{{ service_robots_private_key }}",
            MATCHES_PUBLIC_KEY: "{{ service_robots_matches_public_key }}",
            MATCHES_URL: "https://{{ service_matches_domain }}",
            AUTH_URL: "https://{{ service_auth_domain }}",
            SERVICE: "robots",
            ENV: "{{ env }}",
        },
        # Some parameters are commented as they are inherited in roles
        # registry: "{{ registry }}",
        # registry_username: "{{ registry_username }}",
        # registry_password: "{{ registry_password }}",
        # docker_image: "{{ docker_image }}",
        port_container: "{{ external_port | int }}",
        port_nginx: "{{ internal_port | int }}",
        # domain: "{{ domain }}",
        # cerbot_email: "{{ certbot_email }}",
      }
