- name: Run postgres container
  docker_container:
    name: 'some-postgres'
    restart_policy: 'always'
    published_ports: '5432:5432'
    env:
      POSTGRES_PASSWORD: "{{ password }}"
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    image: postgres:13.0
